### PR TITLE
Fix typos in comments

### PR DESCRIPTION
**Pull request by xiaolou86**

### CODE REVIEW

**Review by webmaster128 — COMMENTED** [review]
This is auto-generated code. To fix them you'd need to fix them in the .proto files on cosmos-sdk, ibc-go, wasmd etc..

**Comment by xiaolou86** [comment]
Take typo `paramaters` for example, I search it in our repo, I can't find any .proto files containing it.

Do you mean they are imported from other repos?

**Comment by webmaster128** [comment]
The proto files are embedded here through git submodules, see https://github.com/confio/cosmjs-types/tree/main/protos

**Comment by xiaolou86** [comment]
wow, got it. Thank you very much.

I will close the PR.

**Comment by xiaolou86** [comment]
close the PR since The proto files are embedded here through git submodules.

**Pull request closed without merging**
