### PR TITLE
codegen: add authz types for bank, staking

### PR DESCRIPTION
**Pull request by boz**
also: bump version

### CODE REVIEW

**Review by webmaster128 — COMMENTED** [review]
Thanks! I'm not familiar with how authz works. Do you only need this change for the two modules? Not more?

Could you please remove the extra zip files? They should not change as long as yarn.lock does not change. Not sure how they popped up. Do you have git LFS set up?


> We use Git for version control. In addition to the well-known basics, we use the extension Git Large File Storage (LFS) to store blobs (currently *.zip). A git-lfs package is available directly in modern package repositories (Debian 10+, Ubuntu 18.04+, Homebrew, MacPorts) and as a backport for older systems. Please see this website for instructions how to install it.

> If you installed git-lfs after cloning this repo, use this command to replace the links with the original files: `git lfs fetch && git lfs checkout`.

**Comment by boz** [comment]
Hey @webmaster128 - Thanks for taking a look!  I think that these were the only two missing built-in authz modules.  I haven't tested it yet, tho.

I *think* I've sorted the `.yarn/` issue - I think that it was indeed from not having installed `git-lfs`

**Comment by webmaster128** [comment]
Thank you

**Comment by webmaster128** [comment]
Released as part of 0.4.1

**Comment by nooomski** [comment]
Hey @webmaster128 , I know this one is merged a while back already, but thought I'd chime in about Authz after reading this PR. There is also a `GenericAuthorization` that needs to be taken into consideration, it's a Msg that takes any Msg url to authorize another account, as specified [here](https://docs.cosmos.network/master/modules/authz/01_concepts.html#Authorization-and-Grant), but I'm not sure if it needs any work on the other modules. Just wanted to let you know in case these types might be missing.

**Comment by webmaster128** [comment]
Not sure when it was added but you find `GenericAuthorization` here: https://github.com/confio/cosmjs-types/blob/v0.4.1/src/cosmos/authz/v1beta1/authz.ts

Please note that the types are generally available in this package but not yet registered by default in CosmJS clients. See https://github.com/cosmos/cosmjs/issues/1026 for the CosmJS integration in the upcoming 0.28.0. But advanced teams can do that manually already.

**Comment by nooomski** [comment]
Ah nice, thanks for that!

**Pull request merged**
