### PR TITLE
add authz types

### PR DESCRIPTION
**Pull request by cmwaters**
This PR adds the proto definitions corresponding to the `authz` module [here](https://github.com/cosmos/cosmos-sdk/tree/v0.44.3/proto/cosmos/authz/v1beta1)

### CODE REVIEW

**Comment by webmaster128** [comment]
Re-opening to trigger CI build after config change. Diff LGTM.

**Comment by webmaster128** [comment]
Could you use `yarn codegen`, which runs prettier on the generated code?

**Comment by cmwaters** [comment]
I get the following errors when using `yarn codegen`:

```
yarn codegen 
Processing wasmd 0.16 proto files ...
google/protobuf/descriptor.proto: File not found.
cosmos_proto/cosmos.proto:4:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
cosmos_proto/cosmos.proto:8:8: "google.protobuf.MessageOptions" is not defined.
cosmos_proto/cosmos.proto: "google.protobuf.MessageOptions" is not defined.
cosmos_proto/cosmos.proto:14:8: "google.protobuf.FieldOptions" is not defined.
gogoproto/gogo.proto:32:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
gogoproto/gogo.proto:38:8: "google.protobuf.EnumOptions" is not defined.
gogoproto/gogo.proto: "google.protobuf.EnumOptions" is not defined.
...
```
It seems like there are some third party proto files that are missing

**Comment by webmaster128** [comment]
Are those errors or warning? Do you get a success error code (`echo $?` must be 0)?

**Comment by webmaster128** [comment]
Could you try

```
git submodule init && git submodule update && yarn && yarn codegen && echo "🚀🚀🚀🚀"
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 124ms
Processing wasmd 0.16 proto files ...
cosmos/base/tendermint/v1beta1/query.proto:4:1: warning: Import gogoproto/gogo.proto is unused.
cosmos/tx/v1beta1/service.proto:7:1: warning: Import gogoproto/gogo.proto is unused.
ibc/core/client/v1/tx.proto:8:1: warning: Import ibc/core/client/v1/client.proto is unused.
Processing wasmd 0.18 proto files ...
cosmos/base/tendermint/v1beta1/query.proto:4:1: warning: Import gogoproto/gogo.proto is unused.
cosmos/tx/v1beta1/service.proto:7:1: warning: Import gogoproto/gogo.proto is unused.
ibc/core/client/v1/tx.proto:8:1: warning: Import ibc/core/client/v1/client.proto is unused.
cosmos/authz/v1beta1/tx.proto:7:1: warning: Import google/protobuf/timestamp.proto is unused.
cosmos/authz/v1beta1/tx.proto:9:1: warning: Import cosmos/base/abci/v1beta1/abci.proto is unused.
cosmos/base/tendermint/v1beta1/query.proto:4:1: warning: Import gogoproto/gogo.proto is unused.
cosmos/upgrade/v1beta1/query.proto:4:1: warning: Import google/protobuf/any.proto is unused.
🚀🚀🚀🚀
```

This works for me on your branch. It includes a bunch of codegen updated that that are needed, like

```diff
+/** Since: cosmos-sdk 0.43 */
```

as well as the formatting.

**Comment by cmwaters** [comment]
Okay I will give it another go. Maybe I don't have the standard google protobuf files on my computer

**Comment by webmaster128** [comment]
Do you have git-lfs installed? See "Checking out code" in https://github.com/cosmos/cosmjs/blob/main/HACKING.md#checking-out-code

**Comment by webmaster128** [comment]
I'll add authz and feegrant in my own PR now based on your work and publish 0.3 with that.

**Pull request closed without merging**
